on:
  workflow_dispatch:
  pull_request:
  schedule:
    - cron: 0 8 1 */3 *
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Rime Clover Pinyin
    permissions:
      contents: write
    steps:
      - name: Set variables
        run: |
          echo "RELEASE_NAME=Released on $(date +%Y%m%d)" >> $GITHUB_ENV
          echo "TAG_NAME=$(date +%Y%m%d)" >> $GITHUB_ENV
        shell: bash

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Prepare Environment
        id: prepare
        run: |
            sudo apt-get update && sudo apt-get install -y git build-essential python3 wget unzip opencc librime-bin curl && wget https://raw.githubusercontent.com/rime/plum/master/rime-install && bash rime-install prelude && python3 -m pip install -U -r requirements.txt

      - name: Build
        run: |
          git submodule update --recursive --remote --rebase && bash ./build.sh && bash ./pack.sh `date +%y%m`

      - uses: actions/upload-artifact@v3
        with:
          name: Packages for release
          path: data/clover.schema-*.zip

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ env.RELEASE_NAME }}
          tag_name: ${{ env.TAG_NAME }}
          prerelease: true
          files: |
            data/clover.schema-*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}